import numpy as np


def cumulant_rms(d, indirect_dim, direct_dim="$B_0$"):
    r"""Return the normalized cumulative RMS change along an indirect axis.

    This diagnostic follows how much the ESR spectrum changes from one
    indirect point to the next.  Smooth alignment should reduce sharp
    horizontal-jitter artifacts, making this cumulant smoother along the
    indirect dimension.

    Specifically, the RMS difference between adjacent spectra is

    .. math::

      \Delta_i = \sqrt{\int |s_{i+1}(B_0)-s_i(B_0)|^2\,dB_0}.

    For a series of :math:`M` spectra, the normalization factor

    .. math::

      N = \frac{1}{M}\sum_{j=1}^{M}
      \sqrt{\int |s_j(B_0)|^2\,dB_0}

    has the same units as :math:`\Delta_i` and enables calculation of the
    cumulant

    .. math::

      C_i = \frac{1}{N}\sum_{k=1}^{i}\Delta_k.

    Thus, :math:`C_i` is dimensionless.

    The discrete implementation uses ``np.diff`` along ``indirect_dim``.
    The common field-axis scale factor cancels, so both integrals use a mean.
    """
    # pyspecdata wraps np.diff with its same-length internal difference helper;
    # the final point is generated by that helper, so drop it explicitly.
    cumulant = (
        d.real.run(np.diff, indirect_dim)[indirect_dim, :-1]
        .run(lambda x: abs(x) ** 2)
        .mean(direct_dim)
        .run(np.sqrt)
    )
    spectrum_rms = (
        d.real.run(lambda x: abs(x) ** 2).mean(direct_dim).run(np.sqrt)
    )
    cumulant.run(np.cumsum, indirect_dim)
    cumulant /= spectrum_rms.mean(indirect_dim)
    return cumulant
