import numpy as np


def cumulant_rms(d, indirect_dim, direct_dim="$B_0$"):
    r"""Return the normalized cumulative RMS change along an indirect axis.

    This diagnostic follows how much the ESR spectrum changes from one
    indirect point to the next.  Smooth alignment should reduce sharp
    horizontal-jitter artifacts, making this cumulant smoother along the
    indirect dimension.

    Each spectrum is normalized to unit RMS amplitude *before* differencing,

    .. math::

      \hat{s}_j(B_0) = \frac{s_j(B_0)}{\sqrt{\int |s_j(B_0)|^2\,dB_0}},

    so that a lineshape comparison is not
    dominated by the narrowest spectra in the
    series.
    (Because ESR spectra are acquired as
    derivatives, a narrow line has much larger
    peak amplitude than a broad line of
    comparable absorption intensity.)
    Without this normalization, the cumulant
    would be biased against detecting real
    shape change in broad, low-intensity
    spectra.

    The RMS difference between adjacent normalized spectra is

    .. math::

      \Delta_i = \sqrt{\int |\hat{s}_{i+1}(B_0)-\hat{s}_i(B_0)|^2\,dB_0},

    which is already dimensionless (each :math:`\hat{s}_j` has unit RMS
    amplitude), giving the cumulant simply as

    .. math::

      C_i = \sum_{k=1}^{i}\Delta_k.

    For a continuously varying spectrum, the corresponding quantity is the
    path length traced by the normalized spectrum.  This discrete sum
    converges toward that sampling-independent path length as the indirect
    axis is sampled more densely.  Very coarse sampling replaces curved
    portions of the path by chords and can therefore underestimate its
    length.  In particular, the intentionally coarse five-spectrum case in
    :ref:`sphx_glr_auto_examples_cumulant_sampling.py` is about 5--6 percent
    below the densely sampled result.  This is sampling discretization, not a
    dependence of the physical units on the number of spectra: the cumulant
    remains dimensionless.

    Along ``direct_dim``, the cumulant is also invariant to the number of
    field-axis points.
    See
    :ref:`sphx_glr_auto_examples_cumulant_field_sampling.py`.

    The discrete implementation uses ``np.diff`` along ``indirect_dim``.
    The common field-axis scale factor cancels, so both integrals use a mean.
    """
    spectrum_rms = (
        d.real.run(lambda x: abs(x) ** 2).mean(direct_dim).run(np.sqrt)
    )
    # pyspecdata wraps np.diff with its same-length internal difference helper;
    # the final point is generated by that helper, so drop it explicitly.
    cumulant = (
        (d.real / spectrum_rms)
        .run(np.diff, indirect_dim)[indirect_dim, :-1]
        .run(lambda x: abs(x) ** 2)
        .mean(direct_dim)
        .run(np.sqrt)
        .run(np.cumsum, indirect_dim)
    )
    return cumulant
